#Arreglos



*   Agrupacion de elementos
*   Son matrices
*   En python utilizamos numpy para representarlos

#Numpy


*   Libreria usada principalmente para ciencia de datos
*   Conjunto de herramientas para diferentes areas como algebra lineal, matrices, estadistica, etc.


##Arreglos en numpy

* Una colección de elementos que son todos del mismo tipo,
* Que tienen una o más dimensiones
* Que son indexados por una tupla de enteros no negativos.

In [ ]:
import numpy as np

In [ ]:
np.concatenate( (np.array([1,2,3]),np.array([2,3,4,5])),axis=0)


array([1, 2, 3, 2, 3, 4, 5])

##Propiedades
* ndim
* shape
* dtype
* size


In [ ]:
arr=np.array([[1,2,3,4],[1,2,3,4]])
estudiante=np.array(["Carlos Loja","Andres Loja","Juan Loja","Pedro Loja"])

In [ ]:
condicion=arr>=3
condicion

array([[False, False,  True,  True],
       [False, False,  True,  True]])

In [ ]:
estudiante[condicion]

array(['Juan Loja', 'Pedro Loja'], dtype='<U11')

In [ ]:
condicion=np.where(arr>=3)
condicion

(array([0, 0, 1, 1]), array([2, 3, 2, 3]))

In [ ]:
estudiante[condicion]

array(['Juan Loja', 'Pedro Loja'], dtype='<U11')

##Ejercicio 1



```
Dispone de una tabla con el desempeño histórico (estadística) de los jugadores equipos (país) que participan en el Mundial de Futbol:



```
![](https://drive.google.com/uc?export=view&id=1P8vssyjKC5S2_uz5Cs4-xoR7E3XGdMO6)
![](https://drive.google.com/uc?export=view&id=1hBTQFB2KKLh2x-LKRZ7MSlASPugR55i0)
![](https://drive.google.com/uc?export=view&id=1e6HP5H55K6iVYdliLuBZAyMSLRiV8Gbz)



In [ ]:
M=np.array([[1,2,3,4],[1,2,3,4]])
promedios=[]
indiceActual=0
indiceFinal=0
for paises in jugadores_paises:
  indiceFinal+=len(paises)
  array=M[0,indiceActual:indiceFinal]
  promedio=np.mean(array)
  indiceActual+=indiceFinal
a=np.array(promedios)
indice=np.argmax(a)
pais=paises[indice]

In [ ]:
paises=np.array(paises)
indice=np.where(paises=="España")[0][0]
indiceInicio=0
for i in range(indice):
  tamanio=len(jugadores_paises[i])
  indiceInicio+=tamanio

indiceFinal=len(jugadores_paises[indice])
efectividad=(M[0,indiceInicio:indiceFinal])/(M[-1,indiceInicio:indiceFinal])
promedio=np.mean(efectividad)
cantidad=len(np.where(efectividad>promedio)[0])

In [ ]:
a=np.array(jugadores_paises[0])
for i in jugadores_paises[1:]:
  a=np.concatenate((a,np.array(i)))
posesion=M[-3,:]
condicion=np.where(posesion>=75)
jugadores=a[condicion]

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
indiceMax=np.argmax(M[-2,:])
indicePais=indiceMax//len(jugadores_paises[0])
pais=paises[indicePais]
nombre=a[indiceMax]

ValueError: ignored

##Ejercicio 2

La fábrica ACME se encarga de fabricar diversos componentes para vehículos. Para esto, tiene varias líneas de fabricación.

Asuma que tiene los siguientes arreglos:



```
P  = np.array(["ct-32", "mto-990", "ct-32"...])
PF = np.array([789, 1500, 900 ...])
PD = np.array([26, 35, 70, ...])
D  = np.array([300, 12, 100, ...])
CF = np.array([1000, 2000, 1100, ...])
```

Donde​ P​ es un arreglo con los códigos de las piezas fabricadas.

El arreglo​ **PF** tiene la cantidad total de piezas fabricadas en el día.

El arreglo​ **PD** indica la cantidad de piezas defectuosas por producto en el día.

El arreglo​ **D** ​indica el día del año de fabricación de la pieza (1 a 365).

Finalmente, el arreglo **​CF** ​indica cuales la capacidad máxima de productos que se pueden fabricar, para cada tipo de pieza, en un día determinado.

​Un mismo producto se puede fabricar varias veces al año pero no varias veces en un mismo día.

**a.** ​Escriba una función llamada​ **produccionAnual**(codigo,P,PF) que retorne la cantidad total de piezas ​código​ fabricadas en el año.

**b.** El rendimiento de fabricación de un producto se mide de la siguiente forma:
>$rendimiento= \frac{total piezas fabricadas−total piezas defectuosas}{total Capacidad}$

Escriba la función **rendimientoPromedio**(codigo, P, PF, PD, CF, D)​ que retorna el rendimientopromedio diario para ​codigo​. El rendimiento promedio diario es igual a rendimiento/total_dias_fabricacion.

**c.** ​Escriba la función ​**porcentajeAnualDefecto**(codigo, P, PD, PF)​, que retorna el porcentaje de defectos que tiene un ​código​. El porcentaje de defectos se calcula como sigue:
>$porcentaje Defectos= \frac{total piezas defectuosas}{total piezas fabricadas}(100)$

**d.** Escriba la función ​**productosDefectuosos**(codigos, P, PF, PD, porcentajemax)​, que retorna un arreglo con los códigos de los productos que están en la lista ​codigos​ y que tengan porcentaje de defectos mayor a l valor dado por la variable «porcentajemax»​.

**e.** ​Escriba la función ​**minimoPorcentajeDefecto**(P, PF, PD)​, que retorna como resultado el código del producto con el menor porcentaje anual de defectos.

##Ejercicio 3
El Black Friday inaugura la temporada de compras navideñas con significativas rebajas en muchas tiendas minoristas y grandes almacenes.

Sucede después de la celebración de Acción de Gracias en Estados Unidos.

Suponga que posee los datos de los productos de una tienda en los siguientes arreglos:

**C**: códigos de todos los productos (cadenas de caracteres).

**P**: precios en dólares para cada uno de los productos (valores con decimales .

**D**: descuentos asociados a cada producto (enteros entre 0 y 100)

**S**: nombre de la sección donde se encuentra cada producto (cadenas de caracteres)

Se requiere implementar las siguientes funciones:

>1.**calcularPrecio**(codigo,C,P,D) que recibe un código y los arreglos C,P,D y retorna el precio final del producto, aplicando el descuento correspondiente.
Para calcular el precio final, aplique las siguiente fórmula:

>$preciofinal=precio-precio*\frac{descuento}{100}$

>2.**calcularTotal**(compras,C,P,D) que recibe una lista de **compras** con los códigos de los productos, los arreglos C,P,D y aplicando todos los descuentos calcula el valor total a **pagar**, .

>3.**hallarSecciones**(**compras**,C,S) que recibe una lista de **compras** con los códigos de los productos, los arreglos C y S y determina las secciones que deberán **visitar** durante las compras. La lista de visitas no tiene elementos repetidos.

>4.**descuentosPorSección** (D,S) que recibe los arrelgos D y S y retorna una **tabla** con el nombre de cada sección y la cantidad de productos que tienen más del 50% de descuento.


Realice un programa que inicialmente muestre una tabla con las secciones y cantidad de productos con más del 50% de descuento. Luego para las compras, permita ingresar los códigos de los productos, procese y muestre el valor total a pagar y las secciones que necesita visitar. El usuario terminará de ingresar las compras escribiendo ‘fin’.

Ejemplos de arreglos:


```
C = ['CTR-2424', 'SKU-5675', 'PSS-4542']
P = [ 56.65, 32.00, 22.22]
D = [0, 50, 10]
S = ['Ropa Niños', 'Juguetes', 'Hombre']
```

